CREATE TABLE public.student (
    id bigint NOT NULL,
    tenant_id character varying(255),
    first_name character varying(255),
    last_name character varying(255)
);

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.student ADD CONSTRAINT student_pkey PRIMARY KEY (id);

ALTER TABLE student ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS student_tenant_isolation_policy ON student;

CREATE POLICY student_tenant_isolation_policy ON student USING (tenant_id = current_setting('app.tenant_id')::VARCHAR);
