version: "3.8"
services:

  postgres:
    image: postgres:14.0
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=springvault
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=vault
    ports:
      - "7358:5432"
    healthcheck:
      test: "pg_isready"

  vault:
    image: vault:1.8.2
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault:/my/vault
    healthcheck:
      test: "nc -z -v localhost 8200"
    command: "vault server -config=/my/vault/config/config.hcl"

  consul:
    image: consul:1.10.2
    container_name: consul
    restart: unless-stopped
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    healthcheck:
      test: "curl -f http://localhost:8500/v1/status/leader || exit 1"
